### ISSUE TITLE
[servo] the first call to `./mach` fails, but subsequent calls work

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/definitely-gp#38]
The first call to `./mach build -r` fails with:

```
Traceback (most recent call last):
  File "./mach", line 103, in <module>
    main(sys.argv)
  File "./mach", line 33, in main
    mach = mach_bootstrap.bootstrap(topdir)
  File "/workspace/servo/python/mach_bootstrap.py", line 288, in bootstrap
    import mach.main
ImportError: No module named mach.main
```

but when you try again, it works.

Thanks to a suggestion from @SimonSapin, I logged `sys.path` just before `/workspace/servo/python/mach_bootstrap.py:288`, which revealed this difference between the two runs:

```diff
--- one.txt     2019-06-28 16:04:52.083072743 +0000
+++ two.txt     2019-06-28 16:15:27.118086735 +0000
@@ -10,17 +10,15 @@
  u'/workspace/servo/python',
  '/workspace/servo',
  '/home/gitpod/.pyenv/versions/2.7.15/lib/python27.zip',
  '/home/gitpod/.pyenv/versions/2.7.15/lib/python2.7',
  '/home/gitpod/.pyenv/versions/2.7.15/lib/python2.7/plat-linux2',
  '/home/gitpod/.pyenv/versions/2.7.15/lib/python2.7/lib-tk',
  '/home/gitpod/.pyenv/versions/2.7.15/lib/python2.7/lib-old',
  '/home/gitpod/.pyenv/versions/2.7.15/lib/python2.7/lib-dynload',
+ '/workspace/.pip-modules/lib/python2.7/site-packages',
+ '/workspace/servo/python/tidy',
  '/home/gitpod/.pyenv/versions/2.7.15/lib/python2.7/site-packages']
-Traceback (most recent call last):
-  File "./mach", line 103, in <module>
-    main(sys.argv)
-  File "./mach", line 33, in main
-    mach = mach_bootstrap.bootstrap(topdir)
-  File "/workspace/servo/python/mach_bootstrap.py", line 290, in bootstrap
-    import mach.main
-ImportError: No module named mach.main
+info: syncing channel updates for 'nightly-2019-05-14-x86_64-unknown-linux-gnu'
+info: latest update on 2019-05-14, rust version 1.36.0-nightly (a9ec99f42 2019-05-13)
+info: downloading component 'rustc'
+^Cmach interrupted by signal or user action. Stopping.
\ No newline at end of file
```

As you can see, the run that fails is missing `'/workspace/.pip-modules/lib/python2.7/site-packages'` and `'/workspace/servo/python/tidy'` in `sys.path`, while the next run that has them works.

I wonder why the first round is missing these. Maybe it's a race condition, related to how Gitpod initializes `/workspace/.pip-modules`?

**Comment by jankeromnes** [comment]
Ok, `sleep 10 && ./mach build -r` did not work:

<img width="1552" alt="Screenshot 2019-07-01 at 12 10 47" src="https://user-images.githubusercontent.com/599268/60428549-5a8f1800-9bf9-11e9-8c2f-c1f46c377255.png">

(Also, the `ports` section in my `.gitpod.yml` seems to be completely ignored, but that's a different bug.)

@AlexTugarev suggested trying to install some `pip` package before running `./mach build -r`, so that the `/workspace/.pip-modules/lib/python2.7/site-packages` directory gets created before hand.

**Comment by jankeromnes** [comment]
The `pip instal requests && ./mach build -r` workaround was successful!

Many thanks Alex. 😄 💯

**Comment by AlexTugarev** [comment]
It still would be nice to understand the underlying issue. a) is it because of of the `--editable` installation, or b) any kind of custom logic to search for modules using a `sys.path` value from before installing the other modules, or c) some general issue with the search paths.

**Comment by SimonSapin** [comment]
On my system, the `mach` Python package (the one that fails to be imported) is at: `~/servo/python/_virtualenv/lib/python2.7/site-packages/mach`, where `~/servo` is the git clone of the Servo repository.

The way `mach_bootstrap.py` works is by creating a virtualenv at `~/servo/python/_virtualenv` if there isn’t one already (installing some Python dependencies), then running mach’s `main()` function. I suspect this “if” is likely the difference between the first and second run.

What I don’t understand is why the `mach` package ends up installed at a location whose path involves `.git-modules` rather than `python/_virtualenv`. You do have a `/workspace/.pip-modules/lib/python2.7/site-packages/mach` directory that contains multiple `.py` files, right? Unfortunately the string `.git-modules` is impossible to usefully look up in a search engine. What tool manages this directory? Does it interfere with `virtualenv`? Can you disable it for Servo?

@AlexTugarev You mention “the `--editiable` installation”, what does this refer to? When `mach_bootstrap.py` runs `pip`, it does not use `--editable`. mach is used by Servo’s build system. Working on the source code of mach itself is almost never what people are interested in when cloning the Servo repository.

**Comment by AlexTugarev** [comment]
@SimonSapin, I mean the `tidy` installation here: https://github.com/servo/servo/blob/master/python/requirements.txt#L35
