### ISSUE TITLE
I do not see any .theia files in here. Are they permitted?

### ISSUE THREAD

**Issue by markfirmware** [gitpod-io/definitely-gp#58]
Along with docker files too.

**Comment by jankeromnes** [comment]
Hi @markfirmware! Unfortunately, `.theia` or `.vscode` configurations are not natively supported in definitely-gp. Only `.gitpod.yml` and Dockerfiles.

(You could technically work around that, by having an `init` task in your `.gitpod.yml` that does something like `mkdir -p .theia && cd .theia && wget ...`, and in that case the `wget` could fetch raw files from the definitely-gp repo, but maybe it's more convenient to check these configuration files into your repository, so that they can be versioned and maintained alongside your code.)
